apiVersion: v1
kind: Service
metadata:
  name: hello-node-service
spec:
  selector:
    app: hello-node
  ports:
  - protocol: "TCP"
  #porta acessivel dentro do cluster
    port: 8082
  #porta acessivel apenas dentro do cluster
    targetPort: 8081
  #porta para acesso de fora do cluster
    nodePort: 30004
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-node-dp
spec:
  selector:
    matchLabels:
      app: hello-node
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
      - name: hello-node
        image: tiagogim/nodejss:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8081